spring:
  application:
    name: networkdeployment
  datasource:
    url: jdbc:h2:file:./nddb;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
