DROP TABLE IF EXISTS PUBLIC.DEVICE_TYPE_ORDERING;
CREATE TABLE PUBLIC.DEVICE_TYPE_ORDERING
(
    DEVICE_TYPE VARCHAR(24) PRIMARY KEY,
    ORDER_KEY   INT
);

INSERT INTO PUBLIC.DEVICE_TYPE_ORDERING(DEVICE_TYPE, ORDER_KEY)
VALUES ('Gateway', 1),
       ('Switch', 2),
       ('Access Point', 3);

DROP TABLE IF EXISTS PUBLIC.DEVICES;
CREATE TABLE PUBLIC.DEVICES
(
    MAC_ADDRESS VARCHAR(24) PRIMARY KEY,
    DEVICE_TYPE VARCHAR(24) NOT NULL,
    UPLINK_MAC_ADDRESS VARCHAR(24),
    FOREIGN KEY (UPLINK_MAC_ADDRESS) REFERENCES DEVICES(MAC_ADDRESS)
);
