DROP TABLE IF EXISTS PUBLIC.DEVICE_TYPE_ORDERING;
CREATE TABLE PUBLIC.DEVICE_TYPE_ORDERING
(
    DEVICE_TYPE VARCHAR(24) PRIMARY KEY,
    ORDER_KEY   INT
);

INSERT INTO PUBLIC.DEVICE_TYPE_ORDERING(DEVICE_TYPE, ORDER_KEY)
VALUES ('Gateway', 1),
       ('Switch', 2),
       ('Access Point', 3);
